/**
 * Générateur de Markdown Professionnel
 *
 * Génère un markdown structuré et détaillé similaire à Landing AI,
 * avec ancres HTML, tableaux, et formatage professionnel
 */

import { v4 as uuidv4 } from 'uuid';
import type { PDFMetadata } from './pdf-metadata-extractor';

export interface ExtractedInvoiceData {
  montant_ht?: number;
  montant_ttc?: number;
  taux_tva?: number;
  date_document?: string;
  date_echeance?: string;
  numero_facture?: string;
  fournisseur?: string;
}

/**
 * Génère un markdown professionnel similaire à Landing AI
 */
/**
 * Nettoie le texte pour supprimer les caractères null et autres caractères problématiques
 */
function cleanText(text: string): string {
  if (!text) return '';

  return text
    .replace(/\u0000/g, '') // Remove null characters
    .replace(/[\x00-\x08\x0B-\x0C\x0E-\x1F\x7F]/g, '') // Remove control characters
    .trim();
}

export function generateProfessionalMarkdown(
  extracted: ExtractedInvoiceData,
  metadata: PDFMetadata,
  fullText: string
): string {
  // Nettoyer le texte complet
  const cleanedFullText = cleanText(fullText);

  let md = '';

  // Fonction helper pour générer un ID d'ancre unique
  const anchor = () => `<a id='${uuidv4()}'></a>\n\n`;

  // ============ EN-TÊTE ============
  md += anchor();
  md += `# Invoice\n\n`;

  // Informations principales
  md += anchor();
  if (extracted.numero_facture) {
    md += `**Invoice number** ${extracted.numero_facture}\n`;
  }
  if (extracted.date_document) {
    md += `**Date of issue** ${formatDate(extracted.date_document)}\n`;
  }
  if (extracted.date_echeance) {
    md += `**Date due** ${formatDate(extracted.date_echeance)}\n`;
  }
  md += `\n`;

  // ============ FOURNISSEUR ============
  if (extracted.fournisseur) {
    md += anchor();
    md += `**From:**\n\n`;
    md += `${cleanText(extracted.fournisseur)}\n\n`;

    // Ajouter les infos du PDF metadata si disponibles
    if (metadata.info.author) {
      md += `Contact: ${cleanText(metadata.info.author)}\n\n`;
    }
  }

  // ============ CLIENT ============
  md += anchor();
  md += `**Bill to:**\n\n`;
  md += `[Client Information]\n\n`;

  // ============ MONTANT DÛ ============
  if (extracted.montant_ttc !== undefined) {
    md += anchor();
    md += `**${formatCurrency(extracted.montant_ttc)} due ${formatDate(extracted.date_echeance || extracted.date_document || '')}**\n\n`;
  }

  // ============ NOTE TVA ============
  if (extracted.taux_tva !== undefined && extracted.taux_tva > 0) {
    md += anchor();
    md += `_TVA: ${extracted.taux_tva}% applicable_\n\n`;
  } else {
    md += anchor();
    md += `_This invoice is issued without VAT (if applicable)._\n\n`;
  }

  // ============ TABLEAU DÉTAILLÉ ============
  md += anchor();
  md += generateInvoiceTable(extracted);
  md += `\n\n`;

  // ============ MÉTADONNÉES DU DOCUMENT ============
  md += anchor();
  md += `---\n\n`;
  md += `## Document Metadata\n\n`;
  md += `| Property | Value |\n`;
  md += `|----------|-------|\n`;
  if (metadata.info.title) {
    md += `| Title | ${metadata.info.title} |\n`;
  }
  md += `| Pages | ${metadata.structure.pageCount} |\n`;
  md += `| File Size | ${(metadata.structure.fileSizeBytes / 1024).toFixed(2)} KB |\n`;
  md += `| PDF Version | ${metadata.structure.pdfVersion || 'N/A'} |\n`;
  md += `| Document Type | ${metadata.content.type} |\n`;
  md += `| Text Length | ${metadata.structure.textLength} characters |\n`;
  md += `| Avg Chars/Page | ${metadata.structure.avgCharsPerPage.toFixed(0)} |\n`;

  if (metadata.info.creator) {
    md += `| Created with | ${metadata.info.creator} |\n`;
  }
  if (metadata.info.producer) {
    md += `| Produced by | ${metadata.info.producer} |\n`;
  }
  if (metadata.info.creationDate) {
    md += `| Created | ${metadata.info.creationDate} |\n`;
  }
  if (metadata.info.modificationDate) {
    md += `| Modified | ${metadata.info.modificationDate} |\n`;
  }

  md += `\n`;

  // ============ INTÉGRITÉ ============
  md += anchor();
  md += `## Document Integrity\n\n`;
  md += `| Hash | Value |\n`;
  md += `|------|-------|\n`;
  md += `| MD5 | \`${metadata.integrity.md5Hash}\` |\n`;
  md += `| SHA-256 | \`${metadata.integrity.sha256Hash}\` |\n`;
  md += `\n`;

  // ============ EXTRACTION INFO ============
  md += anchor();
  md += `## Extraction Information\n\n`;
  md += `- **Provider:** ${metadata.content.recommendation === 'simple-parser' ? 'Simple Text Parser (Free)' : 'OCR Engine'}\n`;
  md += `- **Recommendation:** ${metadata.content.recommendation}\n`;
  md += `- **Duration:** ${metadata.extraction.durationMs}ms\n`;
  md += `- **Extracted at:** ${metadata.extraction.extractedAt}\n`;
  md += `\n`;

  // ============ PIED DE PAGE ============
  md += anchor();
  md += `---\n\n`;
  md += `_Generated by CoreMatch DAF Docs Assistant_\n`;

  return md;
}

/**
 * Génère un tableau HTML pour les détails de la facture
 */
function generateInvoiceTable(data: ExtractedInvoiceData): string {
  const tableId = (suffix: string) => `table-${suffix}`;

  let table = `<table id="${tableId('main')}">\n`;

  // En-tête
  table += `<tr>`;
  table += `<td id="${tableId('h1')}">Description</td>`;
  table += `<td id="${tableId('h2')}">Qty</td>`;
  table += `<td id="${tableId('h3')}">Unit price (excl. tax)</td>`;
  table += `<td id="${tableId('h4')}">Amount (excl. tax)</td>`;
  table += `</tr>\n`;

  // Ligne de détail (si on a les infos)
  table += `<tr>`;
  table += `<td id="${tableId('d1')}">Invoice ${data.numero_facture || 'N/A'}</td>`;
  table += `<td id="${tableId('d2')}">1</td>`;
  table += `<td id="${tableId('d3')}">${data.montant_ht !== undefined ? formatCurrency(data.montant_ht) : 'N/A'}</td>`;
  table += `<td id="${tableId('d4')}">${data.montant_ht !== undefined ? formatCurrency(data.montant_ht) : 'N/A'}</td>`;
  table += `</tr>\n`;

  // Sous-total
  table += `<tr>`;
  table += `<td id="${tableId('s1')}" colspan="3">Subtotal</td>`;
  table += `<td id="${tableId('s2')}">${data.montant_ht !== undefined ? formatCurrency(data.montant_ht) : 'N/A'}</td>`;
  table += `</tr>\n`;

  // TVA
  if (data.taux_tva !== undefined && data.taux_tva > 0) {
    const tvaAmount = data.montant_ht && data.montant_ttc
      ? data.montant_ttc - data.montant_ht
      : 0;

    table += `<tr>`;
    table += `<td id="${tableId('t1')}" colspan="3">VAT (${data.taux_tva}%)</td>`;
    table += `<td id="${tableId('t2')}">${formatCurrency(tvaAmount)}</td>`;
    table += `</tr>\n`;
  }

  // Total
  table += `<tr>`;
  table += `<td id="${tableId('tt1')}" colspan="3"><strong>Total</strong></td>`;
  table += `<td id="${tableId('tt2')}"><strong>${data.montant_ttc !== undefined ? formatCurrency(data.montant_ttc) : 'N/A'}</strong></td>`;
  table += `</tr>\n`;

  // Montant dû
  table += `<tr>`;
  table += `<td id="${tableId('due1')}" colspan="3"><strong>Amount due</strong></td>`;
  table += `<td id="${tableId('due2')}"><strong>${data.montant_ttc !== undefined ? formatCurrency(data.montant_ttc) : 'N/A'}</strong></td>`;
  table += `</tr>\n`;

  table += `</table>`;

  return table;
}

/**
 * Formate une date au format lisible
 */
function formatDate(dateStr: string): string {
  if (!dateStr) return 'N/A';

  try {
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  } catch {
    return dateStr;
  }
}

/**
 * Formate un montant en EUR
 */
function formatCurrency(amount: number): string {
  return `€${amount.toFixed(2)}`;
}
